### ISSUE TITLE
Cannot pass factorization_size param to fmqa.FMBQM.from_data(xs, ys, factorization_size = 8)

### ISSUE THREAD

**Issue by UnixJunkie** [tsudalab/fmqa#7]
Bug?

**Comment by UnixJunkie** [comment]
```
Traceback (most recent call last):
  File "./bin/fmqa_model.py", line 106, in <module>
    trained_model = train_regr(x_list, y_list)
  File "./bin/fmqa_model.py", line 60, in train_regr
    model = fmqa.FMBQM.from_data(xs, ys, factorization_size = 8)
  File "/home/berenger/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 72, in from_data
  File "/home/berenger/.local/lib/python3.8/site-packages/fmqa-0.0.1-py3.8.egg/fmqa/fm_binary_quadratic_model.py", line 35, in __init__
TypeError: __init__() got an unexpected keyword argument 'factorization_size'

```

**Comment by UnixJunkie** [comment]
it looks like an hyper parameter users should be allowed to optimize...
